### ISSUE TITLE
Score-only mode

### ISSUE THREAD

**Issue by RenaKunisaki** [simonlindholm/decomp-permuter#102]
For manual matching it would be great to have a mode that just takes the input files and outputs a score without doing any permuting. This could then be used in a script to display the score each time you make a change, so you can quickly see if you're on the right track.

**Comment by simonlindholm** [comment]
This would be fine to have, but IMO the better fix would be to improve diff.py to include a score of some kind instead. That has some advantages, like not having to compile/objdump twice, and not having to run import.py's complicated compile command line detection and C parsing/serializing. https://github.com/simonlindholm/asm-differ/pull/33 has some work in that direction, would be nice to finish up... There's been some discussion about using the permuter's scoring code as is to get an exact permuter score in diff.py but I'm beginning to suspect that it becomes hard to maintain and we should just approximate it.

**Comment by simonlindholm** [comment]
Does https://github.com/simonlindholm/asm-differ/pull/51 work for you?

**Comment by snuffysasa** [comment]
https://github.com/simonlindholm/decomp-permuter/pull/121

Satisfies this request I believe.

**Comment by simonlindholm** [comment]
and asm-differ also has scoring now.
