### ISSUE TITLE
Quiet mode

### ISSUE THREAD

**Issue by RenaKunisaki** [simonlindholm/decomp-permuter#103]
Sometimes if the permuter isn't finding any improvement for a while, I like to take the best match so far and start manually tweaking it, using diff.py to monitor my progress, but leaving the permuter running in another tab.

Unfortunately since the permuter is constantly printing the latest score, its tab is constantly indicating activity, so I have to periodically check back to see if it's found a better match. It would be nice if this output could be disabled, so the tab's activity indicator would only light up for new matches (or errors, etc).

**Comment by simonlindholm** [comment]
Sounds reasonable. Fixed in c78e5f3603a3d275db7aed2d91c704f3a1733d27.
