### ISSUE TITLE
Support fixed-address declarations

### ISSUE THREAD

**Issue by r-burns** [simonlindholm/decomp-permuter#150]
Some decomp projects use fixed-address declarations for OS memory mapped I/O, like this:

```c
u32 __OSBusClock : 0x800000F8;
```

I think this is nonstandard syntax which is supported by MWCC.

I tried a kludge to pycparser to support this:

```diff
diff --git a/pycparser/c_parser.py b/pycparser/c_parser.py
index 640a759..bc63ea4 100644
--- a/pycparser/c_parser.py
+++ b/pycparser/c_parser.py
@@ -902,6 +902,7 @@ class CParser(PLYParser):
     def p_init_declarator(self, p):
         """ init_declarator : declarator
                             | declarator EQUALS initializer
+                            | declarator COLON constant_expression
         """
         p[0] = dict(decl=p[1], init=(p[3] if len(p) > 2 else None))
 
@@ -914,6 +915,7 @@ class CParser(PLYParser):
     def p_id_init_declarator(self, p):
         """ id_init_declarator : id_declarator
                                | id_declarator EQUALS initializer
+                               | id_declarator COLON constant_expression
         """
         p[0] = dict(decl=p[1], init=(p[3] if len(p) > 2 else None))
 
diff --git a/tests/c_files/c11.c b/tests/c_files/c11.c
index ff11162..e31a650 100644
--- a/tests/c_files/c11.c
+++ b/tests/c_files/c11.c
@@ -18,6 +18,8 @@ _Alignas(32) int q32;
 _Alignas(long long) int qll;
 alignas(64) int qqq;
 
+unsigned int __OSBusClock : 0x800000F8;
+
 static_assert(sizeof(flag) == sizeof(flag2), "Really unexpected size difference");
 
 noreturn void func2(void)
```

Pycparser builds and passes all tests, so it appears to parse that new declaration OK. But when I try to run decomp-permuter on a scratch containing such a declaration, I get a syntax error:

```c
Syntax error in base.c.
before: : at approximately line 152, column 25 (after PERM expansion)

unsigned int OSBusClock : 0x800000F8;
```

This might be a pycparser issue, but I thought I'd ask here first since
* pycparser passes my simple test, so this may be an issue with the way decomp-permuter is using pycparser
* pycparser may not wish to support this nonstandard syntax

**Comment by simonlindholm** [comment]
Hm, having to use a patched pycparser sounds a bit unfortunate. (I don't think they want to accent non-standard language extensions.)

Any chance that the decomps can use some macro for this that gets expanded to nothing during permutation?

(Hard to say what the concrete issue you're running into is without knowing how you hook up permuter to the patched pycparser)

**Comment by r-burns** [comment]
Well, it's possible to expand it to nothing, and we usually wrap these declarations in #ifndef M2CTX. But it messes up the codegen when the address isn't specified, so that's no good for permuting.

I'm applying the above patch to my nixpkgs checkout, so the nix-shell python environment I'm running decomp-permuter in uses that patched pycparser globally.

```diff
--- a/pkgs/development/python-modules/pycparser/default.nix
+++ b/pkgs/development/python-modules/pycparser/default.nix
@@ -9,6 +9,10 @@ buildPythonPackage rec {
     sha256 = "e644fdec12f7872f86c58ff790da456218b10f863970249516d60a5eaca77206";
   };
 
+  patches = [
+    ~/support-fixed-address.patch
+  ];
+
   checkInputs = [ unittestCheckHook ];
 
   unittestFlagsArray = [ "-s" "tests" ];
```

**Comment by simonlindholm** [comment]
> But it messes up the codegen when the address isn't specified, so that's no good for permuting.

PERM_PRETEND and PERM_IGNORE could be used, potentially:
```c
PERM_IGNORE(unsigned int OSBusClock : 0x800000F8;)
PERM_PRETEND(unsigned int OSBusClock;)
```
Putting that behind macros in the actual source code breaks import.py AST minimization, but that could be worked around e.g. by having a post-processing script that transforms `unsigned int OSBusClock = FIXEDADDR(0x800000F8);` (which is syntactically valid C) into the above. Or maybe permuter itself could do that transformation.

**Comment by simonlindholm** [comment]
> Or maybe permuter itself could do that transformation.

I pushed a commit that does essentially this: now `unsigned int OSBusClock = FIXEDADDR(0x800000F8);` gets expanded to `unsigned int OSBusClock : (0x800000F8);` just before compilation. LMK if this is insufficient.

**Comment by r-burns** [comment]
> I pushed a commit that does essentially this: now `unsigned int OSBusClock = FIXEDADDR(0x800000F8);` gets expanded to `unsigned int OSBusClock : (0x800000F8);` just before compilation. LMK if this is insufficient.

I think the equals sign is going to cause problems, it needs to be a part of the macro or it will cause a syntax error when run through mwcc. I think we need something like this:
```c
#ifdef __MWERKS__
#define FIXEDADDR(x) : (x)
#endif
unsigned int OSBusClock FIXEDADDR(0x800000F8);
```

**Comment by simonlindholm** [comment]
Yep, I was thinking something like
```c
#ifdef PERMUTER
#define BLAH(x) = FIXEDADDR(x)
#elif __MWERKS__
#define BLAH(x) : x
#else
#define BLAH(x)
#endif
```

**Comment by r-burns** [comment]
Oh, I see what you mean now. That will work great, thanks!

**Comment by r-burns** [comment]
One more quick question, do I need to do something to get decomp-permuter to define PERMUTER when preprocessing? The example you posted just seems to take the else path when I try it.

**Comment by simonlindholm** [comment]
import.py passes -DPERMUTER when preprocessing, but that change is pretty recent and you might be on an outdated revision. The permuter itself also runs the C preprocessor on the input, entirely without flags, for reasons I'm not sure about... So if you're relying on that that could also be the issue, in which case we could totally add -DPERMUTER to that invocation too.

**Comment by r-burns** [comment]
Ah, that's probably why. I need to keep the mwerks-syntax fixed-address declarations when computing the score, since these fixed-address declarations have different codegen than `*(type*) 0xaddress`. So that only works if I put
```c
#if defined(__MWERKS__)
#define BLAH(x) : x
#else
#define BLAH(x) = FIXEDADDR(x)
#endif
```
in the context.

Would be nice to always define PERMUTER when permuting (but not when computing the score) so that this else case can become a fallback for unrecognized compilers.

**Comment by simonlindholm** [comment]
Ok, done in 95b9d5f926cb0f683e2c5200ea6fd57838f4a87b. I was confused for a bit by your choice of words ("context"? "when computing the score"?) but I guess it comes from you not using import.py normally but rather through the yet unmerged download-from-decomp.me mode.
