### ISSUE TITLE
Getting a 0 score despite differences in stack allotment

### ISSUE THREAD

**Issue by harvestwhisperer** [simonlindholm/decomp-permuter#171]
I've been using the permuter for the Harvest Moon 64 decomp. Recently, I was trying to match a function and got a 0 score from the permuter despite it not actually matching due to differences in the stack pointer allotment, specifically this assembly is different when I `objdump`, there's this difference:

`addiu sp,sp,-24` (permuter) vs. `addiu sp,sp,-8` (original)

The rest of the assembly does match (except for `addiu sp,sp,24` vs. `addiu sp,sp,8` at the end of the function, naturally).

Is the score based on rounding? Is there any setting I can set so this doesn't give me a 0 score?

Thanks!

**Comment by ethteck** [comment]
You can set --stack for this

**Comment by simonlindholm** [comment]
Yep, normally stack diffs are ignored so that introductions of temp vars don't introduce random noise in scoring (making the permuter find improvements that aren't, or not finding ones that are).
