### ISSUE TITLE
Put example of a configured makefile

### ISSUE THREAD

**Issue by H-A-M-G-E-R** [simonlindholm/decomp-permuter#172]
title

**Comment by simonlindholm** [comment]
Sorry, I don't understand

**Comment by H-A-M-G-E-R** [comment]
I can't get the permuter to work, so I opened up this issue

**Comment by H-A-M-G-E-R** [comment]
a makefile configured to be imported with import.py

**Comment by simonlindholm** [comment]
The ones in https://github.com/n64decomp/sm64 and https://github.com/zeldaret/oot work, but they're kinda complex. I don't have a minimal example at hand. The import.py detection mechanism is meant to be somewhat generic, so maybe it can be modified to deal with your makefile? Do you have a repo I can look at?

One thing that import.py does is define PERMUTER=1 when running make, so it's possible to use that to put simplified build rules in place just for the permuter. IIRC some project that had fancy build printouts needed that. And some other projects have their own scripts for creating permuter input directories, that can also be an option if you can't get import.py to work.

**Comment by H-A-M-G-E-R** [comment]
I'm trying to permute some functions in metroid fusion: https://github.com/H-A-M-G-E-R/mf
the ones with the decomp.me links

**Comment by WhenGryphonsFly** [comment]
Just so both of you are aware, there are multiple incompatibilities between the import script and agbcc-compiled code, even when you use permuter_settings.toml to bypass (most of?) the makefile requirements.

I ultimately decided to fork the project, as at least one change would require a separate agbcc-specific codepath regardless. I'm not sure how useful my fork would be, especially with the more recent changes to make it easier for pret-style repos to use it. With that said, [this diff](https://github.com/simonlindholm/decomp-permuter/commit/3f1413a952a2209effd50f1999b1b3e5a087de67) may be a good starting point, although based on your makefile you will need to change the additional flags.

simonlindholm, if you wish to discuss agbcc-related issues further; I can do so here, on a separate issue, or (easiest for me) on the decomp.me discord. Please note that I will unfortunately be AFK for 1~2 hours after this comment.
