### ISSUE TITLE
Support multithreading (-j)

### ISSUE THREAD

**Issue by danebou** [simonlindholm/decomp-permuter#21]
For a fixed permutation set, a multi-threading option would offer a speedup.

**Comment by simonlindholm** [comment]
This would be great. We can probably manage up to 4 threads or so with plain python threading before being bottlenecked by the GIL. We could also add a bash script that runs several instances in parallel, but then coordinating progress logs would be hard.

**Comment by danebou** [comment]
Oh didn't know about GIL. It looks like there are ways around that with `multiprocessing` and `concurrent.futures`

**Comment by danebou** [comment]
The difficulty with the script is it would have to coordinate which subset of the fixed set it would run for each instance.

**Comment by simonlindholm** [comment]
Oh, those libraries look like reasonable solutions indeed (if the GIL is even enough of a problem). Sharing state with a shell script sounds horrible, so yeah, that's another point in favor of doing it within Python. For randomization not having shared state doesn't matter, but of course it's nice to speed up comprehensive bruteforcing as well.
