### ISSUE TITLE
Randomize if conditions

### ISSUE THREAD

**Issue by simonlindholm** [simonlindholm/decomp-permuter#30]
> - `PERM_CONDNEZ(cond)` expands to either `cond` or `(cond) != 0`.

We should do this in the randomizer as well. Similarly, `x == 0` <-> `!x`. (Does `== 1` ever work when there's no explicit compare against 1?)

**Comment by simonlindholm** [comment]
also with != NULL

**Comment by Synray** [comment]
`a > b` sometimes generates different code than `a >= b + 1`

**Comment by simonlindholm** [comment]
f6641b8bd9e19d2893e76789ac17e0c22f046476
